trigger:  none

pool:
  vmImage: 'ubuntu-latest'

variables:
  APP_NAME: 'NodeJs-Backend-12'
  RESOURCE_GROUP: 'myAppRG'

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: ''
    command: 'build'
    Dockerfile: 'server/Dockerfile'
    tags: 'latest'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'MyAzureServiceConnection'
    appType: 'webApp'
    appName: $(APP_NAME)
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    runtimeStack: 'NODE|18-lts'
    startupCommand: 'node dist/index.js'
    resourceGroupName: $(RESOURCE_GROUP)