trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 18'
  inputs:
    versionSpec: '18.x'

- script: |
    cd client
    npm install
    npm run build
  displayName: 'Build React App'

# Debugging Step: List contents to verify build
- script: |
    cd client
    ls -la
  displayName: 'List client directory contents'

- task: AzureWebApp@1
  displayName: 'Deploy React build folder to Azure App Service'
  inputs:
    azureSubscription: 'MyAzureServiceConnection'
    appName: 'ReactJs-Frontend-12'
    package: 'client/dist'
