trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  APP_NAME: 'NodeJs-Backend-12'
  RESOURCE_GROUP: 'myAppRG'

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: 'server/Dockerfile'
    tags: 'latest'

- task: AzureWebAppContainer@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'MyAzureServiceConnection'
    appName: $(APP_NAME)
    containers: '$(APP_NAME):latest'
    resourceGroupName: $(RESOURCE_GROUP)