trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  workspace: 'client'  # Explicit workspace definition

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node 20'

- script: |
    cd $(workspace)
    npm ci --prefer-offline
    npm run build
  displayName: 'Build Project'

- task: PowerShell@2
  displayName: 'Validate Build Output'
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem -Path $(workspace)/dist -Recurse
      Test-Path -Path $(workspace)/dist/index.html

- task: ArchiveFiles@2
  displayName: 'Package Assets'
  inputs:
    rootFolderOrFile: '$(workspace)/dist'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure'
  inputs:
    azureSubscription: 'MyAzureServiceConnection'
    appType: 'webAppLinux'
    appName: 'ReactJs-Frontend-12'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    deploymentMethod: 'zipDeploy'
    # Add startup command here
    startupCommand: 'pm2 serve /home/site/wwwroot --spa --no-daemon'