trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 20'
  inputs:
    versionSpec: '20.x'

- script: |
    cd client
    npm install
    npm run build
  displayName: 'Build React App'

# Debugging Step: Verify build output
- script: |
    cd client
    ls -la dist/
  displayName: 'Verify dist folder exists'

- task: ArchiveFiles@2
  displayName: 'Create deployment package'
  inputs:
    rootFolderOrFile: 'client/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure Web App'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MyAzureServiceConnection'
    WebAppName: 'ReactJs-Frontend-12'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/app.zip'