trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'MyAzureServiceConnection'
  webAppName: 'ReactJs-Frontend-12'

steps:
- task: NodeTool@0
  displayName: 'Use Node 20'
  inputs:
    versionSpec: '20.x'

- script: |
    cd client
    npm ci
    npm run build
  displayName: 'Install dependencies and build'

- script: |
    cd client/dist
    ls -la
  displayName: 'Verify build output'

- task: ArchiveFiles@2
  displayName: 'Create deployment package'
  inputs:
    rootFolderOrFile: 'client/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'webAppLinux'
    appName: $(webAppName)
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    runtimeStack: 'NODE|20-lts'