trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'MyAzureServiceConnection'
  appName: 'NodeJs-Backend-12'
  dockerfilePath: '/sever/Dockerfile'
  imageName: 'appsvc/node:18-lts'

stages:
- stage: BuildAndDeploy
  displayName: Build and Deploy Stage
  jobs:
  - job: BuildAndDeploy
    displayName: Build and Deploy Job
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        tags: |
          latest

    - task: AzureWebAppContainer@1
      displayName: Deploy Docker Image to Azure Web App
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        imageName: $(imageName)
