trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_REPO_NAME: 'myapp/backend'
  IMAGE_TAG: 'latest'

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: ''  # Empty for local build
    command: 'build'
    Dockerfile: 'server/Dockerfile'
    tags: $(IMAGE_TAG)

- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'MyAzureServiceConnection'
    appType: 'webAppContainer'
    appName: 'NodeJs-Backend-12'
    dockerfile: 'server/Dockerfile'
    resourceGroupName: 'myAppRG'
    runtimeStack: 'NODE|18-lts'
    startupCommand: 'node dist/index.js'