trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 18'
  inputs:
    versionSpec: '18.x'

- script: |
    cd client
    npm install
    npm run build
  displayName: 'Build React App'

# Debugging Step: List contents to verify build
- script: |
    cd client
    ls -la
  displayName: 'List client directory contents'

- task: AzureRmWebAppDeployment@4
  
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MyAzureServiceConnection'
    WebAppName: 'ReactJs-Frontend-12'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
  displayName: 'Deploy React build folder to Azure App Service'
