version: '3.8'
services:
  server:
    build: ./server
    container_name: employees_server
    ports:
      - '4000:4000'
    environment:
      # These read from your environment at runtime (e.g., from Azure DevOps variables)
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}